INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Goblin Great', 'ゴブリングレート', 'https://i.imgur.com/zwuns01.png', 1);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Wyvern', 'ワイバーン', 'https://i.imgur.com/gk9MVRp.png', 1);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Landsloth', 'ランドスロース', 'https://i.imgur.com/cxWOMR3.png', 2);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Rai Rai', 'ライライ', 'https://i.imgur.com/6fuBYxF.png', 2);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Wild Gryphon', 'ワイルドグリフォン', 'https://i.imgur.com/czJNbdL.png', 2);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Jackal Thief', 'ジャッカルシーフ', 'https://i.imgur.com/yZ4DSUw.png', 3);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Madam Prism', 'マダムプリズム', 'https://i.imgur.com/bB6sboC.png', 3);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Mega Lapahn', 'メガラパーン', 'https://i.imgur.com/a8ZptMp.png', 3);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Mushu Fushu', 'ムシュフシュ', 'https://i.imgur.com/AwCKG7J.png', 3);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Needle Creep', 'ニードルクリーパー', 'https://i.imgur.com/pymkozu.png', 3);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Orc Chief', 'オークチーフ', 'https://i.imgur.com/s1PnYdG.png', 3);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Raiden', 'ライデン', 'https://i.imgur.com/6xKRDt3.png', 3);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Sea Drake', 'シードレイク', 'https://i.imgur.com/qZuiViW.png', 3);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Sky Walkure', 'スカイワルキューレ', 'https://i.imgur.com/cypBde3.png', 3);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Wraith Lord', 'レイスロード', 'https://i.imgur.com/qlUxRab.png', 3);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Ulfehedinn', 'ウールヴヘジン', 'https://i.imgur.com/WQ3vW25.png', 4);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Cyclops', 'サイクロプス', 'https://i.imgur.com/q6mDmn4.png', 4);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Dark Gargolye', 'ダークガーゴイル', 'https://i.imgur.com/XnN1skf.png', 4);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Maddo Bear', 'マッドベア', 'https://i.imgur.com/4O8KWQ8.png', 4);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Master Senri', 'マスターセンリ', 'https://i.imgur.com/wJCtaZw.png', 4);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Mover', 'ムーバ', 'https://i.imgur.com/brYvJ6c.png', 4);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Nepterion', 'ネプテリオン', 'https://i.imgur.com/P9Sa0lZ.png', 4);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Spirit Horn', 'スピリットホーン', 'https://i.imgur.com/kheQsRd.png', 4);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Titano Turtle', 'ティタノタートル', 'https://i.imgur.com/a9Q02Rb.png', 4);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Tri Rock', 'トライロッカー', 'https://i.imgur.com/YQVApfd.png', 4);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Aquarius', 'アクアリオス', 'https://i.imgur.com/pPBk2w8.png', 5);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Argeti', 'アルゲティ', 'https://i.imgur.com/zBAqbYv.png', 5);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Glutton', 'グラットン', 'https://i.imgur.com/KSiiM7l.png', 5);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Karkinos', 'カルキノス', 'https://i.imgur.com/HE2tdyd.png', 5);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Medusa', 'メデューサ', 'https://i.imgur.com/VKEI0pX.png', 5);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Mesarthim', 'メサルティム', 'https://i.imgur.com/2zmrkpa.png', 5);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Minotaur', 'ミノタウロス', 'https://i.imgur.com/tSDA9Id.png', 5);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Orleon', 'オルレオン', 'https://i.imgur.com/9IN5CX6.png', 5);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Lesathapult', 'レサトパルト', 'https://i.imgur.com/0WAasT1.png', 5);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Sagitarius', 'サジタリウス', 'https://i.imgur.com/GOda0Lk.png', 5);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Torpedon', 'トルペドン', 'https://i.imgur.com/iQK1cNU.png', 5);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Twin Pig', 'ツインピッグス', 'https://i.imgur.com/GO5HNIE.png', 5);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Obsidian Wyvern', 'オブシダンワイバーン', 'https://i.imgur.com/Z4N0V3G.png', 4);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Basilisk', 'バジリスク', 'https://i.imgur.com/OrNN7zB.png', 3);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Sword Cobra', 'ソードコブラ', 'https://i.imgur.com/Jxl12GR.png', 4);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Madam Electra', 'マダムエレクトラ', 'https://i.imgur.com/KtiDiYs.png', 1);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Goblin Rider', 'ゴブリンライダー', 'https://i.imgur.com/bNpPrXZ.png', 2);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Flower Chevalier', 'フラワーシュバリエ', 'https://i.imgur.com/oxMZjv6.png', 4);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Mudgator', 'ドロゲーター', 'https://i.imgur.com/WkpXBtw.png', 3);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Burnsaurus', 'バーンサウルス', 'https://i.imgur.com/qi8sisK.png', 3);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Frost Hound', 'フロストハウンド', 'https://i.imgur.com/H99t70j.png', 1);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Toughgeist', 'タフガイスト', 'https://i.imgur.com/y3OkREz.png', 2);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Rain Spirit', 'レインスピリット', 'https://i.imgur.com/x09w4GG.png', 4);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Flower Madonna', 'フラワーマドンナ', 'https://i.imgur.com/sgX14Ol.png', 4);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Great Golem', 'グレーターゴーレム', 'https://i.imgur.com/J6O7r9n.png', 1);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Venom Salamander', 'ベノムサラマンドラ', 'https://i.imgur.com/JdNYCfz.png', 3);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Storm Ziz', 'ストーム・ジズ', 'https://i.imgur.com/UmF4Jg0.png', 4);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Wild Claw', 'ワイルドクロウ', 'https://i.imgur.com/AvTNi7I.png', 3);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Basilisk Allos', 'バジリスク・アロス', 'https://i.imgur.com/3S5NVX6.png', 4);
INSERT INTO KurikoneCbBot.clan_battle_boss (name, description, image_path, position) VALUES ('Demi Khalid', 'デミ・カリド', 'https://i.imgur.com/1QhirZN.png', 2);
